[package]
name = "parallel_web_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.28", features = ["full"] }
rayon = "1.7"
headless_chrome = "1.0.5"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
scraper ="0.16"
warp = "0.3"
